[package]
name = "myid"
version = "0.1.2"
authors = ["Diyorbek Abdumutalibov <diordev@icloud.com>"]
edition = "2024"
rust-version = "1.93.0"
description = "Rust client library for MyID SDK API — user identification and verification"
documentation = "https://docs.rs/myid"
readme = "README.md"
repository = "https://github.com/diordev/myid"
license = "MIT OR Apache-2.0"
keywords = ["myid", "auth", "faceid", "identification", "uzbekistan"]
categories = ["api-bindings", "authentication"]
include = [
    "README.md",
    "Cargo.toml",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "src/**/*.rs",
    "examples/",
    "tests/",
    ".env.example",
]

[features]
default = ["dotenvy"]
dotenvy = ["dep:dotenvy"]

[dependencies]
thiserror = "2"
url = "2"
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = { version = "0.15", optional = true }
reqwest = { version = "^0.13", features = ["json"], default-features = false }
tokio = { version = "^1", features = ["full"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]

[[example]]
name = "config"
path = "examples/config.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
